import os
import re

from pytest_bdd import given, parsers, scenario, then, when

from tests.bdd.conftest import FEATURES_DIR

FEATURE = os.path.join(FEATURES_DIR, "security.feature")


@scenario(FEATURE, "Workspaces are unreachable without their URL")
def test_workspaces_are_unreachable_without_their_url():
    pass


@given(parsers.parse('workspaces "{label1}" and "{label2}" exist'))
def _two_workspaces_exist(bdd_client, bdd_state, label1, label2):
    for label in (label1, label2):
        workspace_id = bdd_client.post("/api/workspaces").json()["workspace_id"]
        bdd_client.post(
            f"/api/workspaces/{workspace_id}/document",
            files={"file": (f"{label}.txt", f"Secret content for {label}.".encode(), "text/plain")},
        )
        bdd_state[label] = workspace_id


@when('a visitor who only knows "W1"\'s URL interacts with the app', target_fixture="response")
def _visitor_interacts_with_w1(bdd_client, bdd_state):
    return bdd_client.get(f"/api/workspaces/{bdd_state['W1']}/document")


@then('no API response ever includes data belonging to "W2"')
def _no_data_from_w2(response, bdd_state):
    assert bdd_state["W2"] not in response.text
    assert "Secret content for W2" not in response.text


@then("no endpoint enumerates or lists workspace IDs")
def _no_listing_endpoint(bdd_client):
    response = bdd_client.get("/api/workspaces")
    assert response.status_code in (404, 405)


@scenario(FEATURE, "Workspace IDs are cryptographically secure")
def test_workspace_ids_are_cryptographically_secure():
    pass


@when("a new workspace is created", target_fixture="workspace_id")
def _create_new_workspace(bdd_client):
    return bdd_client.post("/api/workspaces").json()["workspace_id"]


@then("the workspace ID must contain at least 128 bits of randomness")
def _at_least_128_bits(workspace_id):
    # token_urlsafe(n) yields ceil(4n/3) base64url chars for n random bytes;
    # 128 bits = 16 bytes -> at least 22 chars.
    assert len(workspace_id) >= 22


@then("the workspace ID must be generated by a cryptographically secure generator")
def _csprng_generated(workspace_id):
    assert re.fullmatch(r"[A-Za-z0-9_-]+", workspace_id)


@then("no sequential or predictable identifiers are exposed in URLs or APIs")
def _not_sequential(bdd_client, workspace_id):
    other_id = bdd_client.post("/api/workspaces").json()["workspace_id"]
    assert other_id != workspace_id
    assert not other_id.startswith(workspace_id[:-1])
