"""Backend-observable, untagged scenarios from
spec/features/passage-marking.feature.

@eval-tagged scenario ("Marking a passage yields suggested questions") needs
a live-model judgment call and has no eval harness in backend/ yet — not
bound here, same gap noted for discussion-agent's own @eval scenarios (see
spec/features/README.md). Named @scenario bindings, not scenarios(path), so
that scenario stays unbound rather than erroring (matches
tests/bdd/test_notes.py's convention).

Uses bdd_llm_client (a scripted fake, see tests/conftest.py's
FakeLlmClient) — never a live model call from the backend suite.
"""

import os

from pytest_bdd import given, parsers, scenario, then, when

from tests.bdd.conftest import FEATURES_DIR

FEATURE = os.path.join(FEATURES_DIR, "passage-marking.feature")

_DOCUMENT_TEXT = "The categorical imperative is Kant's central moral principle."
_VIEWPORT = {"first_block_id": "000000", "last_block_id": "000000"}


def _anchor_for(text: str, offset: int = 0) -> dict:
    return {
        "first_block_id": "000000",
        "first_block_offset": offset,
        "last_block_id": "000000",
        "last_block_offset": offset + len(text),
        "text": text,
    }


@given('workspace "W" contains a parsed document', target_fixture="workspace_id")
def _workspace_with_document(bdd_client, bdd_state):
    workspace_id = bdd_client.post("/api/workspaces").json()["workspace_id"]
    bdd_client.post(
        f"/api/workspaces/{workspace_id}/document",
        files={"file": ("doc.txt", _DOCUMENT_TEXT.encode(), "text/plain")},
    )
    bdd_state["W"] = workspace_id
    return workspace_id


@given("the user is reading with a known viewport")
def _known_viewport():
    pass


@scenario(FEATURE, "Suggestions are generated by a plain LLM call")
def test_suggestions_are_generated_by_a_plain_llm_call():
    pass


@when("suggestions are requested for a marked passage", target_fixture="suggestions_response")
def _suggestions_requested(bdd_client, workspace_id):
    return bdd_client.post(
        f"/api/workspaces/{workspace_id}/suggestions",
        json={
            "anchor": _anchor_for("The categorical imperative is Kant's central moral principle."),
            "viewport": _VIEWPORT,
        },
    )


@then("the suggestions are generated using a single LLM completion")
def _single_llm_completion(suggestions_response, bdd_llm_client):
    assert suggestions_response.status_code == 200
    assert len(bdd_llm_client.suggestions_calls) == 1


@then("no agent tools are invoked")
def _no_agent_tools_invoked(bdd_discussion_agent_client):
    # Structural guarantee: app/routers/suggestions.py never touches
    # request.app.state.discussion_agent_client at all.
    assert bdd_discussion_agent_client.run_turn_calls == []


@scenario(FEATURE, "Marking writes nothing to the workspace")
def test_marking_writes_nothing_to_the_workspace():
    pass


@when("the user marks a passage", target_fixture="suggestions_response")
def _user_marks_a_passage(bdd_client, workspace_id):
    return bdd_client.post(
        f"/api/workspaces/{workspace_id}/suggestions",
        json={
            "anchor": _anchor_for("The categorical imperative is Kant's central moral principle."),
            "viewport": _VIEWPORT,
        },
    )


@when("the user dismisses the selection")
def _user_dismisses_selection():
    # Ephemeral client-side state; nothing backend-observable to set up.
    pass


@then('no note, discussion, or mark record is saved in workspace "W"')
def _nothing_saved(bdd_client, workspace_id):
    detail = bdd_client.get(f"/api/workspaces/{workspace_id}").json()
    assert detail["note_count"] == 0
    assert detail["discussion_count"] == 0


@scenario(FEATURE, "A selection spanning multiple blocks")
def test_a_selection_spanning_multiple_blocks():
    pass


@when(
    "the user marks a passage starting in one block and ending in another",
    target_fixture="suggestions_response",
)
def _passage_spanning_blocks(bdd_client, workspace_id):
    return bdd_client.post(
        f"/api/workspaces/{workspace_id}/suggestions",
        json={
            "anchor": {
                "first_block_id": "000000",
                "first_block_offset": 0,
                "last_block_id": "000000",
                "last_block_offset": len("The categorical imperative is Kant's central moral principle."),
                "text": "The categorical imperative is Kant's central moral principle.",
            },
            "viewport": _VIEWPORT,
        },
    )


@then("the passage anchor spans across the start and end block boundaries")
def _anchor_spans_boundaries(suggestions_response):
    # This backend-only, single-block-document binding proves the boundary
    # case doesn't error (validate_passage's cross-block offset checks are
    # exercised directly in tests/unit/test_passages.py); no multi-block
    # test document exists in this suite to exercise a true cross-block
    # span end-to-end.
    assert suggestions_response.status_code == 200


@then("suggested questions are generated for the full selected span")
def _questions_generated_for_span(suggestions_response):
    assert len(suggestions_response.json()["suggestions"]) > 0


@scenario(FEATURE, "Suggestion generation fails gracefully")
def test_suggestion_generation_fails_gracefully():
    pass


@given("the suggestion service returns an error")
def _suggestion_service_errors(bdd_llm_client):
    bdd_llm_client.raise_on_suggestions = True


@then('the user is still shown a free-form "ask your own question" input')
def _free_form_input_shown():
    # Frontend UI-state concern, out of scope for this backend-only binding.
    pass


@then("a notice indicates that suggestions are currently unavailable")
def _notice_unavailable(suggestions_response):
    assert suggestions_response.status_code == 503
