/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new empty workspace */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workspace"];
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        /** Fetch workspace overview (existence check + metadata + child summaries) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workspace metadata with document status, note and discussion summaries, and journal presence */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete the workspace and all contained data (irreversible) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/document": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        /** Fetch the parsed document (all blocks, ordered) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentView"];
                    };
                };
                /** @description Workspace not found, or no document uploaded yet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Upload the workspace's document (once; immutable thereafter) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description .txt or .md, valid UTF-8, within size limit
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Parsed document */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentView"];
                    };
                };
                /** @description Validation failure (type, size, encoding) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description Workspace already has a document */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get suggested questions for a marked passage (plain LLM call) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        anchor: components["schemas"]["Passage"];
                        viewport: components["schemas"]["Viewport"];
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            suggestions: string[];
                        };
                    };
                };
                400: components["responses"]["InvalidAnchorOrViewport"];
                404: components["responses"]["NotFound"];
                /** @description Workspace has no document yet */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                429: components["responses"]["RateLimited"];
                /** @description LLM unavailable; client falls back to free-form input */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/discussions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        /** List discussions (metadata + anchors, not full turns) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiscussionSummary"][];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /**
         * Create a discussion with its first message, optionally anchored to a passage
         * @description Atomic: the discussion and its first turn are created together, so a failed first turn cannot leave an empty discussion shell behind. The server runs the full agent turn synchronously and responds once with the persisted discussion containing the completed first turn. On failure nothing is persisted.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The first user message of the discussion */
                        message: string;
                        viewport: components["schemas"]["Viewport"];
                        anchor?: components["schemas"]["Passage"];
                    };
                };
            };
            responses: {
                /** @description The created discussion including the completed first turn */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Discussion"];
                    };
                };
                400: components["responses"]["InvalidAnchorOrViewport"];
                404: components["responses"]["NotFound"];
                /** @description Workspace has no document yet */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                429: components["responses"]["RateLimited"];
                502: components["responses"]["AgentFailure"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/discussions/{discussionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                discussionId: components["parameters"]["discussionId"];
            };
            cookie?: never;
        };
        /** Fetch a discussion with all its turns */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                    discussionId: components["parameters"]["discussionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Discussion"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/discussions/{discussionId}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                discussionId: components["parameters"]["discussionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a user message; the completed agent turn is returned
         * @description Synchronous: the server runs the full agent turn (including any tool calls) and responds once with the persisted Turn, which includes the agent response and the tool-call trace. On failure nothing is persisted and a standard error response is returned.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                    discussionId: components["parameters"]["discussionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        message: string;
                        viewport: components["schemas"]["Viewport"];
                    };
                };
            };
            responses: {
                /** @description The completed, persisted turn */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Turn"];
                    };
                };
                400: components["responses"]["InvalidAnchorOrViewport"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
                502: components["responses"]["AgentFailure"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        /** List all notes in the workspace */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Note"][];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Create a note anchored to a passage */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        anchor: components["schemas"]["Passage"];
                        text: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Note"];
                    };
                };
                400: components["responses"]["InvalidAnchorOrViewport"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/notes/{noteId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                noteId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Update a note's text (last write wins) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                    noteId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        text: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Note"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete a note */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                    noteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/journal": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        /** Fetch the current reading journal */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Journal"];
                    };
                };
                /** @description Workspace not found, or no journal generated yet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Generate (or regenerate) the reading journal (plain LLM call) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: components["parameters"]["workspaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New journal, replacing any previous one */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Journal"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description Nothing to synthesize (no notes and no discussion history) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                429: components["responses"]["RateLimited"];
                /** @description LLM unavailable; previous journal, if any, is unchanged */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            message: string;
        };
        Viewport: {
            first_block_id: string;
            last_block_id: string;
        };
        /** @description Identifies a contiguous passage. Offsets are Unicode code-point indices into Block.text; last_block_offset is exclusive. May span blocks (first_block_id <= last_block_id). `text` is the verbatim selected text, kept for display and as an integrity self-check. Validation on write: an anchor referencing an unknown block ID, with an offset beyond the block's length, with first after last, or whose `text` does not match the anchored range is rejected (HTTP 400); nothing is stored. When a passage spans multiple blocks, the anchored range is reconstructed as: the first block's text from first_block_offset to its end, then each full intervening block's text, then the last block's text up to last_block_offset — joined with "\n" between consecutive pieces. */
        Passage: {
            first_block_id: string;
            first_block_offset: number;
            last_block_id: string;
            last_block_offset: number;
            /** @description Kept for display and as a self-check. */
            text: string;
        };
        Workspace: {
            /** @description Capability token: URL-safe, cryptographically random, >= 128 bits of entropy (e.g. 22+ base64url chars). Doubles as the shareable URL path segment. Never sequential. */
            workspace_id: string;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Updated opportunistically on reads; informational only.
             */
            last_accessed_at?: string;
        };
        /** @description Client-facing view of the Document entity: identical minus internal fields (raw_blob_ref), which are never exposed to clients. */
        DocumentView: {
            filename: string;
            /** @enum {string} */
            format: "text" | "markdown";
            size_bytes: number;
            /** Format: date-time */
            uploaded_at: string;
            blocks: components["schemas"]["Block"][];
        };
        Note: {
            note_id: string;
            anchor: components["schemas"]["Passage"];
            text: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Discussion: {
            discussion_id: string;
            /** @description Optional — the passage the discussion started from. */
            anchor?: components["schemas"]["Passage"];
            /** Format: date-time */
            created_at: string;
            turns: components["schemas"]["Turn"][];
        };
        Turn: {
            turn_id: string;
            user_message: string;
            agent_response: string;
            /** @description Viewport visible when this turn occurred. */
            viewport: components["schemas"]["schemas-Viewport"];
            /** @description Trace of tools the agent used this turn, for transparency (rendered client-side as the tool-use trace). Summaries only — raw tool results are NOT persisted; live tool context exists only inside the agent's managed session, and a session rebuilt from Turn records proceeds without past tool results (the agent re-searches if needed). */
            tool_calls?: {
                /** @enum {string} */
                tool: "search_document" | "web_search";
                /** @description A short, human-readable summary of the input (e.g., the query string), designed for client-side rendering of the tool-use trace. */
                input_summary: string;
                /** @description A short, human-readable summary of the result (e.g., number of matches), designed for client-side rendering of the tool-use trace. */
                result_summary?: string;
            }[];
            /** Format: date-time */
            created_at: string;
        };
        /** @description The single current reading journal. Regeneration overwrites it; no version history is kept. */
        Journal: {
            /** @description Markdown-formatted synthesis */
            text: string;
            /** Format: date-time */
            generated_at: string;
        };
        WorkspaceDetail: components["schemas"]["Workspace"] & {
            has_document?: boolean;
            /** @description Computed at read time via a store count/aggregation query; not stored (see data-model.yaml firestore_mapping notes). */
            note_count?: number;
            /** @description Computed at read time via a store count/aggregation query; not stored (see data-model.yaml firestore_mapping notes). */
            discussion_count?: number;
            has_journal?: boolean;
        };
        DiscussionSummary: {
            discussion_id: string;
            anchor?: components["schemas"]["Passage"];
            /** Format: date-time */
            created_at: string;
            /** @description Denormalized counter on the discussion record — set to 1 at atomic discussion creation and incremented in the same batched write that persists each subsequent turn (see data-model.yaml firestore_mapping notes). */
            turn_count: number;
            /** @description Denormalized at atomic discussion creation from the first turn's user message; immutable thereafter (see data-model.yaml firestore_mapping notes). */
            first_message_preview?: string;
        };
        Block: {
            /** @description Zero-padded ordinal ("000000", "000001", ...). Ordering and identity; stable forever because the document is immutable. Padding makes lexicographic order equal numeric order, so IDs sort correctly wherever they are treated as strings (store document IDs, viewport range comparisons). */
            block_id: string;
            /**
             * @description Closed enum — CommonMark block constructs without a type of their own are flattened into these five at parse time (mapping in technical_specification.md §5, upload safety).
             * @enum {string}
             */
            type: "paragraph" | "heading" | "list_item" | "code_block" | "blockquote";
            /** @description Plain text only — canonical string for anchor offsets. No raw HTML, no markup. Sanitization at parse time: raw HTML (blocks and inlines) is dropped entirely; links and all other inline formatting (emphasis, code spans) flatten to their plain text (URLs are discarded) — losing inline styling is a deliberate product decision. Rendering hints (e.g. heading level) live in metadata. */
            text: string;
            /** @description Heading depth; present only for type=heading. */
            level?: number;
        };
        /** @description Identifies the visible range of blocks at a given time. */
        "schemas-Viewport": {
            first_block_id: string;
            last_block_id: string;
        };
    };
    responses: {
        /** @description Unknown ID. Response is identical for nonexistent and malformed IDs; it reveals nothing about other workspaces. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid anchor or viewport — unknown block ID, offset beyond the block's length, first after last, or passage text mismatch. Nothing is stored. */
        InvalidAnchorOrViewport: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Per-workspace or per-IP rate limit exceeded. The Retry-After header indicates when to retry. Previously stored workspace data is unaffected. */
        RateLimited: {
            headers: {
                /** @description Seconds to wait before retrying */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Agent or LLM runtime failure while producing the response; nothing is persisted and the request can be retried. */
        AgentFailure: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        workspaceId: string;
        discussionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
