Feature: Passage marking and suggested questions
  Marking a passage is ephemeral client state; nothing is persisted
  (user-spec §4.1). It produces suggested questions via a plain LLM call.

  Background:
    Given workspace "W" contains a parsed document
    And the user is reading with a known viewport

  @eval
  Scenario: Marking a passage yields suggested questions
    When the user marks a passage in the document
    Then a list of 3 to 5 suggested questions is shown near the selection
    And each suggestion is relevant to the marked passage in its viewport context

  Scenario: Suggestions are generated by a plain LLM call
    When suggestions are requested for a marked passage
    Then the suggestions are generated using a single LLM completion
    And no agent tools are invoked

  Scenario: Marking writes nothing to the workspace
    When the user marks a passage
    And the user dismisses the selection
    Then no note, discussion, or mark record is saved in workspace "W"

  Scenario: A selection spanning multiple blocks
    When the user marks a passage starting in one block and ending in another
    Then the passage anchor spans across the start and end block boundaries
    And suggested questions are generated for the full selected span

  Scenario: Suggestion generation fails gracefully
    Given the suggestion service returns an error
    When the user marks a passage
    Then the user is still shown a free-form "ask your own question" input
    And a notice indicates that suggestions are currently unavailable
