import { expect, test } from "@playwright/test";
import { createWorkspaceViaApi, setLastWorkspaceCookie, startDiscussionViaApi, uploadDocumentViaApi } from "../helpers";

// reading journal: a 404 (no journal yet) shows a CTA; generating renders
// the canned FakeLlmClient markdown; regenerating replaces it.
test("generating and regenerating the reading journal renders markdown", async ({ page, request }) => {
  const workspaceId = await createWorkspaceViaApi(request);
  await uploadDocumentViaApi(request, workspaceId, "doc.md", "# Title\n\nSome content to discuss.");
  await startDiscussionViaApi(request, workspaceId, "What is this about?");
  await setLastWorkspaceCookie(page, workspaceId);

  await page.goto(`/w/${workspaceId}`);
  await page.getByRole("tab", { name: "Journal" }).click();

  const generateButton = page.getByRole("button", { name: /generate a reading journal/i });
  await expect(generateButton).toBeVisible();
  await generateButton.click();

  await expect(page.getByRole("heading", { name: "Reading Journal" })).toBeVisible();
  await expect(
    page.getByText("This is a fake, deterministic journal entry generated by FakeLlmClient"),
  ).toBeVisible();

  const regenerateButton = page.getByRole("button", { name: /regenerate journal/i });
  await expect(regenerateButton).toBeVisible();
  await regenerateButton.click();

  await expect(page.getByRole("heading", { name: "Reading Journal" })).toBeVisible();
});
