"""Production-wireable fake for LlmClient, gated by an env var.

Mirrors app/fake_discussion_agent_client.py's pattern: app/main.py's
create_app() constructs this itself when LLM_FAKE is truthy, so it must
implement the exact call interface routers use (generate_suggestions,
generate_journal) with no test-time scripting hooks, purely from
constructor args and env vars read at call time. It exists to let e2e/UI
work on suggestions and the reading journal proceed without Gemini/Vertex
credentials; it never touches the untrusted-content wrapping that already
happens in the routers before/after the LLM call.
"""

import os

from app.llm_client import LlmUnavailableError

FORCE_ERROR_ENV_VAR = "LLM_FAKE_FORCE_ERROR"

_CANNED_SUGGESTIONS = [
    "What surprised you most about this passage?",
    "How does this connect to something you already believed?",
    "What question would you ask the author here?",
    "Where do you agree or disagree with this idea?",
]

_CANNED_JOURNAL_MARKDOWN = (
    "## Reading Journal\n\n"
    "This is a fake, deterministic journal entry generated by "
    "FakeLlmClient for tests and e2e runs.\n"
)


def _force_error() -> bool:
    return os.environ.get(FORCE_ERROR_ENV_VAR, "").lower() in ("1", "true")


class FakeLlmClient:
    def generate_suggestions(self, prompt: str) -> list[str]:
        if _force_error():
            raise LlmUnavailableError("Simulated LLM failure (fake client sentinel env var).")
        return list(_CANNED_SUGGESTIONS)

    def generate_journal(self, prompt: str) -> str:
        if _force_error():
            raise LlmUnavailableError("Simulated LLM failure (fake client sentinel env var).")
        return _CANNED_JOURNAL_MARKDOWN
